spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://DCS106BDBKH096:3306/ktln_bkend?useTimezone=true&serverTimezone=UTC
    username: root
    password: dahPhai2to@ok0eS
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
